name = "fragrant-term-4318"
main = "src/index.ts"
compatibility_date = "2024-11-06"

[vars]
ALLOWED_ORIGIN = "https://mamamansion-ar2.pages.dev"
BOOKING_URL    = "https://mamamansion-ar2.pages.dev/"
MAPS_URL       = "https://maps.app.goo.gl/T7Ho9VkyG452BD1p7"
FB_PAGE_URL    = "https://www.facebook.com/MamaMansion37/"
MM_GAS_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbyUJpLq0qumPl5B4szrNFBZdmVr3RN_y5pFmiRVOwpW_kkbwIgIXHL_MowlNjF97yqx/exec"
APPS_SCRIPT_URL   = "https://script.google.com/macros/s/AKfycbyUJpLq0qumPl5B4szrNFBZdmVr3RN_y5pFmiRVOwpW_kkbwIgIXHL_MowlNjF97yqx/exec"
PAYRENT_GAS_URL    = "https://script.google.com/macros/s/AKfycbwneoLD2XjHCFrCqodqDmy62PDAUjPwN3aG_GTA3VWpsB86W2Q6iPh8qKYSq6WdDNLL7w/exec"
MOVEOUT_GAS_URL    = "https://script.google.com/macros/s/AKfycbzjrKP2Rzko6sTMNsFwYzQBf2PS938RlnHBJp_9Gi98WfhVOp1xUxkHqx7BAGAJtoax/exec"
# HOWTO_IMAGE_URL_1 = ""
# HOWTO_IMAGE_URL_2 = ""

[[kv_namespaces]]
binding = "KV"
id = "a3650d699e944f65944cf935c869aaa3"
