name = "fragrant-term-4318"
main = "src/index.ts"
compatibility_date = "2025-08-08"

[vars]
ALLOWED_ORIGIN = "https://mamamansion-ar2.pages.dev"
BOOKING_URL    = "https://mamamansion-ar2.pages.dev/"
MAPS_URL       = "https://maps.app.goo.gl/Qktm2mDGPappQ8EZA"
FB_PAGE_URL    = "https://www.facebook.com/MamaMansion37/"
MM_GAS_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbxVd8Iy3f9t6FuRItt8n9lRlQGNeseAHiC3UicBmdF4XKu0fTWV0pHm_8G3ERY0mafepA/exec"
APPS_SCRIPT_URL   = "https://script.google.com/macros/s/AKfycbxVd8Iy3f9t6FuRItt8n9lRlQGNeseAHiC3UicBmdF4XKu0fTWV0pHm_8G3ERY0mafepA/exec"
PAYRENT_GAS_URL    = "https://script.google.com/macros/s/AKfycbwneoLD2XjHCFrCqodqDmy62PDAUjPwN3aG_GTA3VWpsB86W2Q6iPh8qKYSq6WdDNLL7w/exec"
MOVEOUT_GAS_URL    = "https://script.google.com/macros/s/AKfycbzjrKP2Rzko6sTMNsFwYzQBf2PS938RlnHBJp_9Gi98WfhVOp1xUxkHqx7BAGAJtoax/exec"
HOWTO_IMAGE_URL_1 = "https://drive.google.com/uc?export=view&id=146RJw9oS4fr1gEMiqrePMTwS-bXZYcZJ"
HOWTO_IMAGE_URL_2 = "https://drive.google.com/uc?export=view&id=1Y6KUvNmw0wkBoSCldHNA38sBvrDniuR3"


[[kv_namespaces]]
binding = "KV"
id = "a3650d699e944f65944cf935c869aaa3"
